function modelPath = build_eea_simulink_starter(modelName, outputFolder)
%BUILD_EEA_SIMULINK_STARTER Create a simple closed-loop Simulink starter model.

arguments
    modelName (1, :) char = 'eea_starter_model'
    outputFolder (1, :) char = pwd
end

if ~isfolder(outputFolder)
    mkdir(outputFolder);
end

modelName = matlab.lang.makeValidName(modelName);
modelPath = fullfile(outputFolder, [modelName '.slx']);

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end

if exist(modelPath, 'file')
    delete(modelPath);
end

new_system(modelName);
open_system(modelName);

set_param(modelName, ...
    'StopTime', '5', ...
    'Solver', 'ode45', ...
    'SignalLogging', 'on', ...
    'SignalLoggingName', 'logsout');

add_block('simulink/Sources/Step', [modelName '/Reference'], ...
    'Time', '0.5', ...
    'Before', '0', ...
    'After', '1', ...
    'Position', [60 80 90 110]);

add_block('simulink/Math Operations/Sum', [modelName '/Error'], ...
    'Inputs', '+-', ...
    'Position', [140 78 165 112]);

add_block('simulink/Continuous/PID Controller', [modelName '/Controller'], ...
    'P', '2', ...
    'I', '5', ...
    'D', '0', ...
    'Position', [215 70 295 120]);

add_block('simulink/Discontinuities/Saturation', [modelName '/Actuator Limit'], ...
    'UpperLimit', '10', ...
    'LowerLimit', '-10', ...
    'Position', [345 75 390 115]);

add_block('simulink/Continuous/Transfer Fcn', [modelName '/Plant'], ...
    'Numerator', '[1]', ...
    'Denominator', '[0.2 1]', ...
    'Position', [440 75 525 115]);

add_block('simulink/Sinks/Scope', [modelName '/Scope'], ...
    'Position', [600 62 630 93]);

add_block('simulink/Sinks/To Workspace', [modelName '/yout'], ...
    'VariableName', 'yout', ...
    'SaveFormat', 'StructureWithTime', ...
    'Position', [600 122 660 153]);

add_line(modelName, 'Reference/1', 'Error/1', 'autorouting', 'on');
add_line(modelName, 'Error/1', 'Controller/1', 'autorouting', 'on');
add_line(modelName, 'Controller/1', 'Actuator Limit/1', 'autorouting', 'on');
add_line(modelName, 'Actuator Limit/1', 'Plant/1', 'autorouting', 'on');
add_line(modelName, 'Plant/1', 'Scope/1', 'autorouting', 'on');
add_line(modelName, 'Plant/1', 'yout/1', 'autorouting', 'on');
add_line(modelName, 'Plant/1', 'Error/2', 'autorouting', 'on');

save_system(modelName, modelPath);
end
